{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.overrun",
    "module": "AtionGradle",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AtionGradle-1.0.0.jar",
          "url": "AtionGradle-1.0.0.jar",
          "size": 39531,
          "sha512": "8c330109ea644774df8464f6e06cfc9cc7065ee4d330b7b83857d2ca8143d546468060288c14b5dedb1ab88976222ec1811c3c9a48d1d51705e2a5a08eeee73a",
          "sha256": "ad84465921f37f7a82caba5b70a6d61ff5d3c2cc2af6339409ed1b95e3f2a7a1",
          "sha1": "dacbaae91335fd680f4cd02492106ef602e164c2",
          "md5": "1089b36ec8aee2946070fb42b84ea05c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "AtionGradle-1.0.0.jar",
          "url": "AtionGradle-1.0.0.jar",
          "size": 39531,
          "sha512": "8c330109ea644774df8464f6e06cfc9cc7065ee4d330b7b83857d2ca8143d546468060288c14b5dedb1ab88976222ec1811c3c9a48d1d51705e2a5a08eeee73a",
          "sha256": "ad84465921f37f7a82caba5b70a6d61ff5d3c2cc2af6339409ed1b95e3f2a7a1",
          "sha1": "dacbaae91335fd680f4cd02492106ef602e164c2",
          "md5": "1089b36ec8aee2946070fb42b84ea05c"
        }
      ]
    }
  ]
}
