{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.overrun",
    "module": "ation-gradle",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ation-gradle-1.0.0.jar",
          "url": "ation-gradle-1.0.0.jar",
          "size": 40897,
          "sha512": "22c19877d867a6e4bf237795abea4b48b1a0dcb0263022967ddaf6af967f4774ed80aca3c77258e325c7825752de056e2aa5fb3de74ccfa9618531bcc504422e",
          "sha256": "ab355a1872cd68185a10680dcd41e4e13932efc61e0d60d6f14b141930f55224",
          "sha1": "4110918eae01db19a5dd9181235553aa433738c7",
          "md5": "5ee52d932b1f52a2820d5be306e48012"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "ation-gradle-1.0.0.jar",
          "url": "ation-gradle-1.0.0.jar",
          "size": 40897,
          "sha512": "22c19877d867a6e4bf237795abea4b48b1a0dcb0263022967ddaf6af967f4774ed80aca3c77258e325c7825752de056e2aa5fb3de74ccfa9618531bcc504422e",
          "sha256": "ab355a1872cd68185a10680dcd41e4e13932efc61e0d60d6f14b141930f55224",
          "sha1": "4110918eae01db19a5dd9181235553aa433738c7",
          "md5": "5ee52d932b1f52a2820d5be306e48012"
        }
      ]
    }
  ]
}
