{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.overrun",
    "module": "ation-gradle",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ation-gradle-1.0.0.jar",
          "url": "ation-gradle-1.0.0.jar",
          "size": 18730,
          "sha512": "5d693b970d97183796f5d48b54451b8753b822195ebcfb82096258f141abedf989675ec1af101fd45371890788193a77da37cf2f48d896d85f8087840a992a0f",
          "sha256": "99253a1053286c73a4e07cfbc6d0188f0eb4717c1ab41c9c9a1fbe6ad8570833",
          "sha1": "aa246d041b89e3c1fb882250298dac4f0a43a1e6",
          "md5": "0f7a129acd72dbb33d9b7b90c0dfd12e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ation-gradle-1.0.0.jar",
          "url": "ation-gradle-1.0.0.jar",
          "size": 18730,
          "sha512": "5d693b970d97183796f5d48b54451b8753b822195ebcfb82096258f141abedf989675ec1af101fd45371890788193a77da37cf2f48d896d85f8087840a992a0f",
          "sha256": "99253a1053286c73a4e07cfbc6d0188f0eb4717c1ab41c9c9a1fbe6ad8570833",
          "sha1": "aa246d041b89e3c1fb882250298dac4f0a43a1e6",
          "md5": "0f7a129acd72dbb33d9b7b90c0dfd12e"
        }
      ]
    }
  ]
}
